/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2020 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


#include "stm32l4xx.h"
#include "gpio_driver.h"
#include <stdint.h>

int main(void)
{
	GPIO_Handle_t button = {{GPIOC}, {GPIO_PIN_NO_0, GPIO_MODE_IT_FT, GPIO_VHIGH_SPEED, GPIO_PIN_PU }};
	GPIO_Handle_t led    = {{GPIOC}, {GPIO_PIN_NO_1, GPIO_MODE_OUT  , GPIO_VHIGH_SPEED, GPIO_PIN_PU, GPIO_OP_TYPE_PP}};

	GPIO_ClockControl(GPIOC, ENABLE);
	GPIO_Init(&button);
	GPIO_Init(&led);

	GPIO_PriorityConfig(EXTI0_IRQ_N0, 1);
	GPIO_IRQITConfig(EXTI0_IRQ_N0, ENABLE);

	while(1);

}


void EXTI0_IRQHandler()
{
	//Handle the interrupt
	// pass the pin
	GPIO_IRQHandling(0);

	GPIO_WriteTogglePin(GPIOC, GPIO_PIN_NO_1);
}
